### ISSUE TITLE
Home page blocks with images not aligned properly

### ISSUE THREAD

**Issue by click2tman** [click2tman/embassyofsl#3]
The blurb images on the homepage are not aligned properly on all screens. If you look closely, you will notice the shadow on top of the image is sometimes, larger than the image itself. For screens less than 1024px and when the mobile menu is applied and used, these images should flush left and right. In short their width should be 100% and hight automatically set and as a result touching both edges of the screen. I have attached the issue and correction design
[embassy-of-sl-in-usa-mobile-flush-images.pdf](https://github.com/click2tman/embassyofsl/files/299574/embassy-of-sl-in-usa-mobile-flush-images.pdf)
<img width="328" alt="screen shot 2016-06-05 at 8 13 51 pm" src="https://cloud.githubusercontent.com/assets/1200007/15809248/c10501f2-2b5a-11e6-9635-303b5bfd5022.png">
<img width="627" alt="screen shot 2016-06-05 at 8 13 18 pm" src="https://cloud.githubusercontent.com/assets/1200007/15809249/c12a3d14-2b5a-11e6-9708-c978892e4230.png">
<img width="577" alt="screen shot 2016-06-05 at 8 13 00 pm" src="https://cloud.githubusercontent.com/assets/1200007/15809250/c18d0a8e-2b5a-11e6-8cc3-64c1cc4794f2.png">

**Comment by saurabhd** [comment]
Accomplished, please check and let me know your thoughts.

**Comment by click2tman** [comment]
The alignment is much better now but the images are not filling the whole span of the width. I want all of these images to be 100% wide just like the top most image. No white space on the left and right. White space should only be on the text blocks below the image for readabiliity

**Comment by saurabhd** [comment]
Changed images width to touching both edges of the screen without white space. Please review.

**Comment by click2tman** [comment]
This is complete.
